name: Release Erlang Libraries
on:
  push:
    branches: [master]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Setup swagger-codegen
        uses: valitydev/action-setup-swagger-codegen@v0.0.4
        with:
          codegen-version: "2.4.25"
          generator-version: "1.1.0"

      - run: npm install

      - name: Bundle spec
        run: npm run build

      - name: Generate stubs
        run: |
          mkdir -p out
          echo "Generate apikeys stubs"
          swagger-codegen generate -l vality-erlang-client -i web_deploy/swagger.json -o out/erlang-client-apikeys --additional-properties packageName=swag_client_apikeys
          swagger-codegen generate -l vality-erlang-server -i web_deploy/swagger.json -o out/erlang-server-apikeys --additional-properties packageName=swag_server_apikeys

      - name: Deploy erlang-client-apikeys artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: release/erlang/client/master
          folder: out/erlang-client-apikeys
          commit-message: Release ${{ github.repository }}@${{ github.sha }}

      - name: Deploy erlang-server-apikeys artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: release/erlang/server/master
          folder: out/erlang-server-apikeys
          commit-message: Release ${{ github.repository }}@${{ github.sha }}
